# publishing
exclude:
  - README.md
  - LICENSE
  - CNAME
  - run.local

# plugins
gems:
  - jekyll-sitemap # generates standart sitemaps
  - jekyll-redirect-from # redirects on pages
  - jekyll-mentions
  - jemoji

# content processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: false # this should be the same as highlighter
highlighter: pygments
sass:
  style: :compressed
  sass_dir: _sass

# routes
baseurl: "/"
permalink: /blog/:title/

# site properties
disqus: julioc # disqus shortname (find it on the Settings page)
google_analytics: UA-30488321-1 # tracking code (e.g. UA-2110908-2)
name: Júlio César
description: Brazilian Software Developer
blog_info: "Coging, games, hacking (and everything else)"
